//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preston.Media {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Preston.Media.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio encryption.
        /// </summary>
        internal static string FrameDescAENC {
            get {
                return ResourceManager.GetString("FrameDescAENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached picture.
        /// </summary>
        internal static string FrameDescAPIC {
            get {
                return ResourceManager.GetString("FrameDescAPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended buffer size.
        /// </summary>
        internal static string FrameDescBUF {
            get {
                return ResourceManager.GetString("FrameDescBUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play counter.
        /// </summary>
        internal static string FrameDescCNT {
            get {
                return ResourceManager.GetString("FrameDescCNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string FrameDescCOM {
            get {
                return ResourceManager.GetString("FrameDescCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string FrameDescCOMM {
            get {
                return ResourceManager.GetString("FrameDescCOMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial frame.
        /// </summary>
        internal static string FrameDescCOMR {
            get {
                return ResourceManager.GetString("FrameDescCOMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio encryption.
        /// </summary>
        internal static string FrameDescCRA {
            get {
                return ResourceManager.GetString("FrameDescCRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted meta frame.
        /// </summary>
        internal static string FrameDescCRM {
            get {
                return ResourceManager.GetString("FrameDescCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption method registration.
        /// </summary>
        internal static string FrameDescENCR {
            get {
                return ResourceManager.GetString("FrameDescENCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalization.
        /// </summary>
        internal static string FrameDescEQU {
            get {
                return ResourceManager.GetString("FrameDescEQU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalization.
        /// </summary>
        internal static string FrameDescEQUA {
            get {
                return ResourceManager.GetString("FrameDescEQUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event timing codes.
        /// </summary>
        internal static string FrameDescETC {
            get {
                return ResourceManager.GetString("FrameDescETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event timing codes.
        /// </summary>
        internal static string FrameDescETCO {
            get {
                return ResourceManager.GetString("FrameDescETCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General encapsulated object.
        /// </summary>
        internal static string FrameDescGEO {
            get {
                return ResourceManager.GetString("FrameDescGEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General encapsulated object.
        /// </summary>
        internal static string FrameDescGEOB {
            get {
                return ResourceManager.GetString("FrameDescGEOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group identification registration.
        /// </summary>
        internal static string FrameDescGRID {
            get {
                return ResourceManager.GetString("FrameDescGRID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involved people list.
        /// </summary>
        internal static string FrameDescIPL {
            get {
                return ResourceManager.GetString("FrameDescIPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Involved people list.
        /// </summary>
        internal static string FrameDescIPLS {
            get {
                return ResourceManager.GetString("FrameDescIPLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked information.
        /// </summary>
        internal static string FrameDescLINK {
            get {
                return ResourceManager.GetString("FrameDescLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked information.
        /// </summary>
        internal static string FrameDescLNK {
            get {
                return ResourceManager.GetString("FrameDescLNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music CD identifier.
        /// </summary>
        internal static string FrameDescMCDI {
            get {
                return ResourceManager.GetString("FrameDescMCDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music CD Identifier.
        /// </summary>
        internal static string FrameDescMCI {
            get {
                return ResourceManager.GetString("FrameDescMCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG location lookup table.
        /// </summary>
        internal static string FrameDescMLL {
            get {
                return ResourceManager.GetString("FrameDescMLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPEG location lookup table.
        /// </summary>
        internal static string FrameDescMLLT {
            get {
                return ResourceManager.GetString("FrameDescMLLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership frame.
        /// </summary>
        internal static string FrameDescOWNE {
            get {
                return ResourceManager.GetString("FrameDescOWNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play counter.
        /// </summary>
        internal static string FrameDescPCNT {
            get {
                return ResourceManager.GetString("FrameDescPCNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached picture.
        /// </summary>
        internal static string FrameDescPIC {
            get {
                return ResourceManager.GetString("FrameDescPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularimeter.
        /// </summary>
        internal static string FrameDescPOP {
            get {
                return ResourceManager.GetString("FrameDescPOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularimeter.
        /// </summary>
        internal static string FrameDescPOPM {
            get {
                return ResourceManager.GetString("FrameDescPOPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position synchronisation frame.
        /// </summary>
        internal static string FrameDescPOSS {
            get {
                return ResourceManager.GetString("FrameDescPOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private frame.
        /// </summary>
        internal static string FrameDescPRIV {
            get {
                return ResourceManager.GetString("FrameDescPRIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended buffer size.
        /// </summary>
        internal static string FrameDescRBUF {
            get {
                return ResourceManager.GetString("FrameDescRBUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverb.
        /// </summary>
        internal static string FrameDescREV {
            get {
                return ResourceManager.GetString("FrameDescREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative volume adjustment.
        /// </summary>
        internal static string FrameDescRVA {
            get {
                return ResourceManager.GetString("FrameDescRVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative volume adjustment.
        /// </summary>
        internal static string FrameDescRVAD {
            get {
                return ResourceManager.GetString("FrameDescRVAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverb.
        /// </summary>
        internal static string FrameDescRVRB {
            get {
                return ResourceManager.GetString("FrameDescRVRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized lyric/text.
        /// </summary>
        internal static string FrameDescSLT {
            get {
                return ResourceManager.GetString("FrameDescSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced tempo codes.
        /// </summary>
        internal static string FrameDescSTC {
            get {
                return ResourceManager.GetString("FrameDescSTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized lyric/text.
        /// </summary>
        internal static string FrameDescSYLT {
            get {
                return ResourceManager.GetString("FrameDescSYLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized tempo codes.
        /// </summary>
        internal static string FrameDescSYTC {
            get {
                return ResourceManager.GetString("FrameDescSYTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album/Movie/Show title.
        /// </summary>
        internal static string FrameDescTAL {
            get {
                return ResourceManager.GetString("FrameDescTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album/Movie/Show title.
        /// </summary>
        internal static string FrameDescTALB {
            get {
                return ResourceManager.GetString("FrameDescTALB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM (Beats Per Minute).
        /// </summary>
        internal static string FrameDescTBP {
            get {
                return ResourceManager.GetString("FrameDescTBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPM (beats per minute).
        /// </summary>
        internal static string FrameDescTBPM {
            get {
                return ResourceManager.GetString("FrameDescTBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        internal static string FrameDescTCM {
            get {
                return ResourceManager.GetString("FrameDescTCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type.
        /// </summary>
        internal static string FrameDescTCO {
            get {
                return ResourceManager.GetString("FrameDescTCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        internal static string FrameDescTCOM {
            get {
                return ResourceManager.GetString("FrameDescTCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type.
        /// </summary>
        internal static string FrameDescTCON {
            get {
                return ResourceManager.GetString("FrameDescTCON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright message.
        /// </summary>
        internal static string FrameDescTCOP {
            get {
                return ResourceManager.GetString("FrameDescTCOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright message.
        /// </summary>
        internal static string FrameDescTCR {
            get {
                return ResourceManager.GetString("FrameDescTCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string FrameDescTDA {
            get {
                return ResourceManager.GetString("FrameDescTDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string FrameDescTDAT {
            get {
                return ResourceManager.GetString("FrameDescTDAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist delay.
        /// </summary>
        internal static string FrameDescTDLY {
            get {
                return ResourceManager.GetString("FrameDescTDLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist delay.
        /// </summary>
        internal static string FrameDescTDY {
            get {
                return ResourceManager.GetString("FrameDescTDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded by.
        /// </summary>
        internal static string FrameDescTEN {
            get {
                return ResourceManager.GetString("FrameDescTEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoded by.
        /// </summary>
        internal static string FrameDescTENC {
            get {
                return ResourceManager.GetString("FrameDescTENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyricist/Text writer.
        /// </summary>
        internal static string FrameDescTEXT {
            get {
                return ResourceManager.GetString("FrameDescTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        internal static string FrameDescTFLT {
            get {
                return ResourceManager.GetString("FrameDescTFLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        internal static string FrameDescTFT {
            get {
                return ResourceManager.GetString("FrameDescTFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string FrameDescTIM {
            get {
                return ResourceManager.GetString("FrameDescTIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string FrameDescTIME {
            get {
                return ResourceManager.GetString("FrameDescTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content group description.
        /// </summary>
        internal static string FrameDescTIT1 {
            get {
                return ResourceManager.GetString("FrameDescTIT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title/songname/content description.
        /// </summary>
        internal static string FrameDescTIT2 {
            get {
                return ResourceManager.GetString("FrameDescTIT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle/Description refinement.
        /// </summary>
        internal static string FrameDescTIT3 {
            get {
                return ResourceManager.GetString("FrameDescTIT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial key.
        /// </summary>
        internal static string FrameDescTKE {
            get {
                return ResourceManager.GetString("FrameDescTKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial key.
        /// </summary>
        internal static string FrameDescTKEY {
            get {
                return ResourceManager.GetString("FrameDescTKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language(s).
        /// </summary>
        internal static string FrameDescTLA {
            get {
                return ResourceManager.GetString("FrameDescTLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language(s).
        /// </summary>
        internal static string FrameDescTLAN {
            get {
                return ResourceManager.GetString("FrameDescTLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string FrameDescTLE {
            get {
                return ResourceManager.GetString("FrameDescTLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string FrameDescTLEN {
            get {
                return ResourceManager.GetString("FrameDescTLEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media type.
        /// </summary>
        internal static string FrameDescTMED {
            get {
                return ResourceManager.GetString("FrameDescTMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media type.
        /// </summary>
        internal static string FrameDescTMT {
            get {
                return ResourceManager.GetString("FrameDescTMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original artist(s)/performer(s).
        /// </summary>
        internal static string FrameDescTOA {
            get {
                return ResourceManager.GetString("FrameDescTOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original album/movie/show title.
        /// </summary>
        internal static string FrameDescTOAL {
            get {
                return ResourceManager.GetString("FrameDescTOAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original filename.
        /// </summary>
        internal static string FrameDescTOF {
            get {
                return ResourceManager.GetString("FrameDescTOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original filename.
        /// </summary>
        internal static string FrameDescTOFN {
            get {
                return ResourceManager.GetString("FrameDescTOFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Lyricist(s)/text writer(s).
        /// </summary>
        internal static string FrameDescTOL {
            get {
                return ResourceManager.GetString("FrameDescTOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original lyricist(s)/text writer(s).
        /// </summary>
        internal static string FrameDescTOLY {
            get {
                return ResourceManager.GetString("FrameDescTOLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original artist(s)/performer(s).
        /// </summary>
        internal static string FrameDescTOPE {
            get {
                return ResourceManager.GetString("FrameDescTOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original release year.
        /// </summary>
        internal static string FrameDescTOR {
            get {
                return ResourceManager.GetString("FrameDescTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original release year.
        /// </summary>
        internal static string FrameDescTORY {
            get {
                return ResourceManager.GetString("FrameDescTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original album/Movie/Show title.
        /// </summary>
        internal static string FrameDescTOT {
            get {
                return ResourceManager.GetString("FrameDescTOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File owner/licensee.
        /// </summary>
        internal static string FrameDescTOWN {
            get {
                return ResourceManager.GetString("FrameDescTOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group.
        /// </summary>
        internal static string FrameDescTP1 {
            get {
                return ResourceManager.GetString("FrameDescTP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band/Orchestra/Accompaniment.
        /// </summary>
        internal static string FrameDescTP2 {
            get {
                return ResourceManager.GetString("FrameDescTP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor/Performer refinement.
        /// </summary>
        internal static string FrameDescTP3 {
            get {
                return ResourceManager.GetString("FrameDescTP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreted, remixed, or otherwise modified by.
        /// </summary>
        internal static string FrameDescTP4 {
            get {
                return ResourceManager.GetString("FrameDescTP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of a set.
        /// </summary>
        internal static string FrameDescTPA {
            get {
                return ResourceManager.GetString("FrameDescTPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string FrameDescTPB {
            get {
                return ResourceManager.GetString("FrameDescTPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead performer(s)/Soloist(s).
        /// </summary>
        internal static string FrameDescTPE1 {
            get {
                return ResourceManager.GetString("FrameDescTPE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band/orchestra/accompaniment.
        /// </summary>
        internal static string FrameDescTPE2 {
            get {
                return ResourceManager.GetString("FrameDescTPE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductor/performer refinement.
        /// </summary>
        internal static string FrameDescTPE3 {
            get {
                return ResourceManager.GetString("FrameDescTPE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreted, remixed, or otherwise modified by.
        /// </summary>
        internal static string FrameDescTPE4 {
            get {
                return ResourceManager.GetString("FrameDescTPE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of a set.
        /// </summary>
        internal static string FrameDescTPOS {
            get {
                return ResourceManager.GetString("FrameDescTPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string FrameDescTPUB {
            get {
                return ResourceManager.GetString("FrameDescTPUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISRC (International Standard Recording Code).
        /// </summary>
        internal static string FrameDescTRC {
            get {
                return ResourceManager.GetString("FrameDescTRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track number/Position in set.
        /// </summary>
        internal static string FrameDescTRCK {
            get {
                return ResourceManager.GetString("FrameDescTRCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording dates.
        /// </summary>
        internal static string FrameDescTRD {
            get {
                return ResourceManager.GetString("FrameDescTRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording dates.
        /// </summary>
        internal static string FrameDescTRDA {
            get {
                return ResourceManager.GetString("FrameDescTRDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track number/Position in set.
        /// </summary>
        internal static string FrameDescTRK {
            get {
                return ResourceManager.GetString("FrameDescTRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet radio station name.
        /// </summary>
        internal static string FrameDescTRSN {
            get {
                return ResourceManager.GetString("FrameDescTRSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet radio station owner.
        /// </summary>
        internal static string FrameDescTRSO {
            get {
                return ResourceManager.GetString("FrameDescTRSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FrameDescTSI {
            get {
                return ResourceManager.GetString("FrameDescTSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FrameDescTSIZ {
            get {
                return ResourceManager.GetString("FrameDescTSIZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISRC (international standard recording code).
        /// </summary>
        internal static string FrameDescTSRC {
            get {
                return ResourceManager.GetString("FrameDescTSRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software/hardware and settings used for encoding.
        /// </summary>
        internal static string FrameDescTSS {
            get {
                return ResourceManager.GetString("FrameDescTSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software/Hardware and settings used for encoding.
        /// </summary>
        internal static string FrameDescTSSE {
            get {
                return ResourceManager.GetString("FrameDescTSSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content group description.
        /// </summary>
        internal static string FrameDescTT1 {
            get {
                return ResourceManager.GetString("FrameDescTT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title/Songname/Content description.
        /// </summary>
        internal static string FrameDescTT2 {
            get {
                return ResourceManager.GetString("FrameDescTT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle/Description refinement.
        /// </summary>
        internal static string FrameDescTT3 {
            get {
                return ResourceManager.GetString("FrameDescTT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyricist/text writer.
        /// </summary>
        internal static string FrameDescTXT {
            get {
                return ResourceManager.GetString("FrameDescTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined text information frame.
        /// </summary>
        internal static string FrameDescTXX {
            get {
                return ResourceManager.GetString("FrameDescTXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined text information frame.
        /// </summary>
        internal static string FrameDescTXXX {
            get {
                return ResourceManager.GetString("FrameDescTXXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string FrameDescTYE {
            get {
                return ResourceManager.GetString("FrameDescTYE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string FrameDescTYER {
            get {
                return ResourceManager.GetString("FrameDescTYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique file identifier.
        /// </summary>
        internal static string FrameDescUFI {
            get {
                return ResourceManager.GetString("FrameDescUFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique file identifier.
        /// </summary>
        internal static string FrameDescUFID {
            get {
                return ResourceManager.GetString("FrameDescUFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsychronized lyric/text transcription.
        /// </summary>
        internal static string FrameDescULT {
            get {
                return ResourceManager.GetString("FrameDescULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        internal static string FrameDescUSER {
            get {
                return ResourceManager.GetString("FrameDescUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsychronized lyric/text transcription.
        /// </summary>
        internal static string FrameDescUSLT {
            get {
                return ResourceManager.GetString("FrameDescUSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official audio file webpage.
        /// </summary>
        internal static string FrameDescWAF {
            get {
                return ResourceManager.GetString("FrameDescWAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official artist/performer webpage.
        /// </summary>
        internal static string FrameDescWAR {
            get {
                return ResourceManager.GetString("FrameDescWAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official audio source webpage.
        /// </summary>
        internal static string FrameDescWAS {
            get {
                return ResourceManager.GetString("FrameDescWAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial information.
        /// </summary>
        internal static string FrameDescWCM {
            get {
                return ResourceManager.GetString("FrameDescWCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial information.
        /// </summary>
        internal static string FrameDescWCOM {
            get {
                return ResourceManager.GetString("FrameDescWCOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright/Legal information.
        /// </summary>
        internal static string FrameDescWCOP {
            get {
                return ResourceManager.GetString("FrameDescWCOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright/Legal information.
        /// </summary>
        internal static string FrameDescWCP {
            get {
                return ResourceManager.GetString("FrameDescWCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official audio file webpage.
        /// </summary>
        internal static string FrameDescWOAF {
            get {
                return ResourceManager.GetString("FrameDescWOAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official artist/performer webpage.
        /// </summary>
        internal static string FrameDescWOAR {
            get {
                return ResourceManager.GetString("FrameDescWOAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official audio source webpage.
        /// </summary>
        internal static string FrameDescWOAS {
            get {
                return ResourceManager.GetString("FrameDescWOAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official internet radio station homepage.
        /// </summary>
        internal static string FrameDescWORS {
            get {
                return ResourceManager.GetString("FrameDescWORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string FrameDescWPAY {
            get {
                return ResourceManager.GetString("FrameDescWPAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers official webpage.
        /// </summary>
        internal static string FrameDescWPB {
            get {
                return ResourceManager.GetString("FrameDescWPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers official webpage.
        /// </summary>
        internal static string FrameDescWPUB {
            get {
                return ResourceManager.GetString("FrameDescWPUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined URL link frame.
        /// </summary>
        internal static string FrameDescWXX {
            get {
                return ResourceManager.GetString("FrameDescWXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined URL link frame.
        /// </summary>
        internal static string FrameDescWXXX {
            get {
                return ResourceManager.GetString("FrameDescWXXX", resourceCulture);
            }
        }
    }
}
