//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ID3AlbumArtFixer.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int AlbumArtImageQualityPerCent
        {
            get
            {
                return ((int)(this["AlbumArtImageQualityPerCent"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumArtFixerIncludeSubfolders
        {
            get
            {
                return ((bool)(this["AlbumArtFixerIncludeSubfolders"]));
            }
            set
            {
                this["AlbumArtFixerIncludeSubfolders"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetAlbumArtSecurity
        {
            get
            {
                return ((bool)(this["SetAlbumArtSecurity"]));
            }
            set
            {
                this["SetAlbumArtSecurity"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Backup Operators")]
        public string FullControlAccount
        {
            get
            {
                return ((string)(this["FullControlAccount"]));
            }
            set
            {
                this["FullControlAccount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Users")]
        public string ReadOnlyAccount
        {
            get
            {
                return ((string)(this["ReadOnlyAccount"]));
            }
            set
            {
                this["ReadOnlyAccount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SkipWelcomePage
        {
            get
            {
                return ((bool)(this["SkipWelcomePage"]));
            }
            set
            {
                this["SkipWelcomePage"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateResizeAlbumArt
        {
            get
            {
                return ((bool)(this["CreateResizeAlbumArt"]));
            }
            set
            {
                this["CreateResizeAlbumArt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RestrictAlbumArtAccess
        {
            get
            {
                return ((bool)(this["RestrictAlbumArtAccess"]));
            }
            set
            {
                this["RestrictAlbumArtAccess"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EmbedAlbumArt
        {
            get
            {
                return ((bool)(this["EmbedAlbumArt"]));
            }
            set
            {
                this["EmbedAlbumArt"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumArtFromLargestImage
        {
            get
            {
                return ((bool)(this["AlbumArtFromLargestImage"]));
            }
            set
            {
                this["AlbumArtFromLargestImage"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlbumArtFromFile
        {
            get
            {
                return ((string)(this["AlbumArtFromFile"]));
            }
            set
            {
                this["AlbumArtFromFile"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640, 640")]
        public global::System.Drawing.Size AlbumArtMaxSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["AlbumArtMaxSize"]));
            }
            set
            {
                this["AlbumArtMaxSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640, 640")]
        public global::System.Drawing.Size EmbedImageMaxSize
        {
            get
            {
                return ((global::System.Drawing.Size)(this["EmbedImageMaxSize"]));
            }
            set
            {
                this["EmbedImageMaxSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Folder.jpg")]
        public string EmbedFileName
        {
            get
            {
                return ((string)(this["EmbedFileName"]));
            }
            set
            {
                this["EmbedFileName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte EmbedImageType
        {
            get
            {
                return ((byte)(this["EmbedImageType"]));
            }
            set
            {
                this["EmbedImageType"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Scanned CD Cover")]
        public string EmbedImageDescription
        {
            get
            {
                return ((string)(this["EmbedImageDescription"]));
            }
            set
            {
                this["EmbedImageDescription"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmbedDeleteImages
        {
            get
            {
                return ((string)(this["EmbedDeleteImages"]));
            }
            set
            {
                this["EmbedDeleteImages"] = value;
            }
        }
    }
}
